version: '3.9'
services:
  app:
    platform: linux/x86_64
    build: . # 현재위치의 Dockerfile을 참조
    image: petlink:latest #deadwhale/petlink:latest
    ports:
      - "8080:8080"
    command:
      - --spring.profiles.active=local # for dev profile