version: '3.9'
services:
  app:
    image: deadwhale/petlink:0.1.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis     # Resource Lock storage
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
