version: '3.9'
services:
  app:
    platform: linux/x86_64
    image: deadwhale/petlink:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis     # Resource Lock storage
  redis:
    platform: linux/x86_64
    image: redis:alpine
    ports:
      - "6379:6379"
