# DB properties
spring:
  datasource:
    driver-class-name: ${database.driver}
    url: ${database.host}
    username: ${database.user}
    password: ${database.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      jwt:
        port: ${redis.jwt.port}

# AWS properties
logging:
  level:
    org.hibernate.type: trace

# JWT properties
jwt:
  secret-key: ${jwt.secret.key}
  expire-length: ${jwt.expire.length}
  prefix: ${jwt.prefix}
  header: ${jwt.header}

# Object Storage properties
storage:
  access-key: ${storage.access.key}
  secret-key: ${storage.secret.key}

worker:
  id: 1

data:
  center:
    id: 1

