# DB properties
spring:
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

# AWS properties
logging:
  level:
    org.hibernate.type: trace

# JWT properties
jwt:
  secret-key: flab-project-petlink-secret-key-sample
  expire-length: 86400000

# Object Storage properties
storage:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}

worker:
  id: ${WORKER_ID}

data:
  center:
    id: ${DATA_CENTER_ID}

