server:
  port: 8080

spring:
  profiles:
    default: local
---
spring:
  config:
    activate:
      on-profile: local,dev,prod

# log level 설정 (debug, info, warn, error)
logging:
  level:
    org.hibernate.type: trace

worker:
  id: 1

data:
  center:
    id: 1
