# DB properties
spring:
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

  data:
    redis:
      host: 118.67.133.150
      port: 6379


# AWS properties
logging:
  level:
    org.hibernate.type: trace

# JWT properties
jwt:
  secret-key: flab-project-petlink-secret-key-sample
  expire-length: 86400000 # 1 days

