# DB properties
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create-drop
  data:
    redis:
      host: # 레디스 주소
      port: # 레디스 포트

  profiles:
    active: dev # dev, prod , test


# AWS properties
logging:
  level:
    org.hibernate.type: trace

# JWT properties
jwt:
  secret-key: flab-project-petlink-secret-key-sample
  expire-length: 86400000

# Object Storage properties
storage:
  access-key: mock-access-key
  secret-key: mock-secret-key

worker:
  id: 1

data:
  center:
    id: 1

