spring:
  application:
    name: module-funding
  # DB properties
  datasource:
    driver-class-name: ${database.driver}
    url: ${database.host}
    username: ${database.user}
    password: ${database.password}
  jpa:
    database-platform: ${database.platform}
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update # create-drop, create, update, validate, none
server:
  port: 9003

fegin:
  url:
    prefix: http://localhost:9000
