name: Docker CD

on:
  push:
    branches:
      - main

  # 실제 실행될 내용들을 정의합니다.
  jobs:
    build:
      runs-on: ubuntu-latest # ubuntu 최신 버전에서 script를 실행

    steps:
      # 지정한 저장소(현재 REPO)에서 코드를 워크플로우 환경으로 가져오도록 하는 github action
      - uses: actions/checkout@v4

      - name: copy to env file #깃헙 설정에 복사한 ENV 값을 모두 .env file로 만든다.
        run: |
          touch .env
          echo "${{ secrets.ENV }}" >> .env

      - name: create remote directory # ec2 서버에 디렉토리를 하나 만들어준다.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APP_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_GENERAL_SSH_KEY }}
          script: mkdir -p /home/ubuntu/app/petlink

      - name: copy project # ssh key를 이용해 현재 푸시된 소스를 서버에 복사한다.
        uses: burnett01/rsync-deployments@6.0
        with:
          switches: -avzr --delete
          remote_path: /home/ubuntu/srv/ubuntu/
          remote_host: ${{ secrets.APP_SERVER_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.AWS_GENERAL_SSH_KEY }}
