name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_review_comment:
    types: [ created, edited ] # 리뷰 코멘트가 생성되거나 수정되었을 때 실행

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean

